//
//  MockMovieMindsService().swift
//  MovieMinds
//
//  Created by Lahori, Divyansh on 10/06/24.
//

import Foundation

class MockMovieMindsService: MovieMindsService {
    
    override func getMoviesData(sectionType: MainScreenSection) async -> ([MovieModel], MainScreenSection) {
        // Mock data for different section types
        switch sectionType {
        case .trendingByDay:
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .trendingByDay)
        case .trendingByWeek:
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .trendingByWeek)
        case .nowPlaying:
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .nowPlaying)
        case .popular:
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .popular)
        case .topRated:
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .topRated)
        case .trending:
            // return some default trending movies
            return ([MovieModel(id: 321,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Dunkirk",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451),
                     MovieModel(id: 323,
                                adult: false,
                                backdrop_path: "",
                                original_title: "",
                                overview: "",
                                popularity: 5460.2,
                                poster_path: "",
                                release_date: "",
                                title: "Unbeaten",
                                video: false,
                                vote_average: 7.8,
                                vote_count: 23451)], .trending)
        }
    }
}
